
enum TAGS {
_42_INN = 0x42,         		// 0x 42, Issuer Identification Number (IIN), template 0x BF0C|73
_4F_ADF = 0x4F,         		// 0x 4F, Application Dedicated File (ADF) Name, template 0x 61,
_50_APP_LABEL = 0x50,   		// 0x 50, Application Label, template 0x 61|A5
_57_T2_EQ_DATA = 0x57,  		// 0x 57, Track 2 Equivalent Data, template 0x 70|77
_5a_PAN = 0x5a,         		// 0x 5A, Application Primary Account Number (PAN), template 0x 70|77
_5F20_CARD_HOLDER_NAME = 0x5F20,	// 0x 5F20, Cardholder Name, template 0x 70|77
_F24_APP_EXP_DATE = 0xF24,        // 0x 5F24, Application Expiration Date, template 0x 70|77
_5F25_APP_EFF_DATE = 0x5F25,		// 0x 5F25, Application Effective Date, template 0x 70|77
_5F28_ISSUER_COUNTRY_CODE = 0x5F28,	// 0x 5F28, Issuer Country Code, template 0x 70|77
_5F2A_TRANSACTION_CURRENCY_CODE = 0x5F2A,		// 0x 5F2A, Transaction Currency Code, template 0x -
_5F2D_LANG_PREFERENCE = 0x5F2D,		// 0x 5F2D, Language Preference, template 0x A5
_5F30_SERVICE_CODE = 0x5F30,		// 0x 5F30, Service Code , template 0x 70|77
_5F34_PAN = 0x5F34,		        // 0x 5F34, Application Primary Account Number (PAN) Sequence Number, template 0x 70|77
_5F36_TRANSACTION_CURENCY_EXPONENT = 0x5F36,		// 0x 5F36, Transaction Currency Exponent, template 0x -
_5F50_ISSUER_URL = 0x5F50,		// 0x 5F50, Issuer URL, template 0x BF0C|73
_5F53_IBAN = 0x5F53,		// 0x 5F53, International Bank Account Number (IBAN), template 0x BF0C|73
_5F54_BIC = 0x5F54,		// 0x 5F54, Bank Identifier Code (BIC), template 0x BF0C|73
_5F55_ISSUER_COUNTRY_CODE_A2F = 0x5F55,		// 0x 5F55, Issuer Country Code (alpha2 format), template 0x BF0C|73
_5F56_ISSUER_COUNTRY_CODE_A3F = 0x5F56,		// 0x 5F56, Issuer Country Code (alpha3 format), template 0x BF0C|73
_5F57_ACCOUNT_TYPE = 0x5F57,		// 0x 5F57, Account Type, template 0x -
_61_APP_TEMPLATE = 0x61,		// 0x 61, Application template, template 0x 70|77
_6F_FCI = 0x6F,		// 0x 6F, File Control Information (FCI), template 0x -
_70_READ_RECORD_RESPONSE_MESSAGE = 0x70,		// READ RECORD Response Message Template, template 0x -
_71_ISSUER_SCRIPT_TEMPLATE_1 = 0x71,		// Issuer Script Template 1, template 0x -
_72_ISSUER_SCRIPT_TEMPLATE_2 = 0x72,		// Issuer Script Template 2, template 0x -
_73_DIRECTORY_DISCRETIONARY_TEMPLATE = 0x73,		// Directory Discretionary Template, template 0x 61
_77_RESPONSE_MESSAGE_TEMPLATE_FORMAT_2 = 0x77,		// Response Message Template Format 2, template 0x -
_80_RESPONSE_MESSAGE_TEMPLATE_FORMAT_1 = 0x80,		// Response Message Template Format 1, template 0x -
_81_AMOUNT_AUTHORISED = 0x81,		// Amount, Authorised (Binary), template 0x -
_82_APPLICATION_INTERCHANGE_PROFILE = 0x82,		// APPLICATION INTERCHANGE PROFILE, TEMPLATE 0X 77|80
_83_COMMAND_TEMPLATE = 0x83,		// Command Template, template 0x -
_84_DEDICATED_FILE_DF_NAME = 0x84,		// Dedicated File (DF) Name, template 0x 6F
_86_ISSUER_SCRIPT_COMMAND = 0x86,		// Issuer Script Command, template 0x 71|72
_87_APPLICATION_PRIORITY_INDICATOR = 0x87,		// Application Priority Indicator, template 0x 61|A5
_88_SHORT_FILE_IDENTIFIER_SFI = 0x88,		// Short File Identifier (SFI), template 0x A5
_89_AUTHORISATION_CODE = 0x89,		// Authorisation Code, template 0x -
_8A_AUTHORISATION_RESPONSE_CODE = 0x8A,		// Authorisation Response Code, template 0x -
_8C_CARD_RISK_MANAGEMENT_DATA_OBJECT_LIST1_CDOL1 = 0x8C,		// Card Risk Management Data Object List1 (CDOL1), template 0x 70|77
_8D_CARD_RISK_MANAGEMENT_DATA_OBJECT_LIST2_CDOL2 = 0x8D,		// Card Risk Management Data Object List 2 (CDOL2), template 0x 70|77
_8E_CARDHOLDER_VERIFICATION_METHOD_CVM_LIST = 0x8E,		// Cardholder Verification Method (CVM) List, template 0x 70|77
_8F_CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX = 0x8F,		// Certification Authority Public Key Index, template 0x 70|77
_90_ISSUER_PUBLIC_KEY_CERTIFICATE = 0x90,		// Issuer Public Key Certificate, template 0x 70|77
_91_ISSUER_AUTHENTICATION_DATA = 0x91,		// Issuer Authentication Data, template 0x -
_92_ISSUER_PUBLIC_KEY_REMAINDER = 0x92,		// Issuer Public Key Remainder, template 0x 70|77
_93_SIGNED_STATIC_APPLICATION_DATA = 0x93,		// Signed Static Application Data, template 0x 70|77
_94_APPLICATION_FILE_LOCATOR_AFL = 0x94,		// Application File Locator (AFL), template 0x 77|80
_95_TERMINAL_VERIFICATION_RESULTS = 0x95,		// Terminal Verification Results, template 0x -
_97_TRANSACTION_CERTIFICATE_DATA_OBJECT_LIST_TDOL = 0x97,		// Transaction Certificate Data Object List (TDOL), template 0x 70|77
_98_TRANSACTION_CERTIFICATE_TC_HASH_VALUE = 0x98,		// Transaction Certificate (TC) Hash Value, template 0x -
_99_TRANSACTION_PERSONAL_IDENTIFICATION_NUMBER_PIN_DATA = 0x99,		// Transaction Personal Identification Number (PIN) Data, template 0x -
_9A_TRANSACTION_DATE = 0x9A,		// Transaction Date, template 0x -
_9B_TRANSACTION_STATUS_INFORMATION = 0x9B,		// Transaction Status Information, template 0x -
_9C_TRANSACTION_TYPE = 0x9C,		// Transaction Type, template 0x -
_9D_DIRECTORY_DEFINITION_FILE_DDF_NAME = 0x9D,		// Directory Definition File (DDF) Name, template 0x 61
_9F01_ACQUIRER_IDENTIFIER = 0x9F01,		// Acquirer Identifier, template 0x -
_9F02_AMOUNT_AUTHORISED_NUMERIC = 0x9F02,		// Amount, Authorised (Numeric), template 0x -
_9F03_AMOUNT_OTHER_NUMERIC = 0x9F03,		// Amount, Other (Numeric), template 0x -
_9F04_AMOUNT_OTHER_BINARY = 0x9F04,		// Amount, Other (Binary), template 0x -
_9F05_APPLICATION_DISCRETIONARY_DATA = 0x9F05,		// Application Discretionary Data, template 0x 70|77
_9F06_APPLICATION_IDENTIFIER_AID_TERMINAL = 0x9F06,		// Application Identifier (AID) -terminal, template 0x -
_9F07_APPLICATION_USAGE_CONTROL = 0x9F07,		// Application Usage Control, template 0x 70|77
_9F08_APPLICATION_VERSION_NUMBER_T = 0x9F08,		// Application Version Number, template 0x 70|77
_9F09_APPLICATION_VERSION_NUMBER = 0x9F09,		// Application Version Number, template 0x -
_9F0B_CARDHOLDER_NAME_EXTENDED = 0x9F0B,		// Cardholder Name Extended, template 0x 70|77
_9F0D_ISSUER_ACTION_CODE_DEFAULT = 0x9F0D,		// Issuer Action Code - Default, template 0x 70|77
_9F0E_ISSUER_ACTION_CODE_DENIAL = 0x9F0E,		// Issuer Action Code -Denial, template 0x 70|77
_9F0F_ISSUER_ACTION_CODE_ONLINE_ = 0x9F0F,		// Issuer Action Code - Online , template 0x 70|77
_9F10_ISSUER_APPLICATION_DATA = 0x9F10,		// Issuer Application Data, template 0x 77|80
_9F11_ISSUER_CODE_TABLE_INDEX = 0x9F11,		// Issuer Code Table Index, template 0x A5
_9F12_APPLICATION_PREFERRED_NAME = 0x9F12,		// Application Preferred Name, template 0x 61|A5
_9F13_LAST_ONLINE_APPLICATION_TRANSACTION_COUNTER_ATC_REGISTER = 0x9F13,		// Last Online Application Transaction Counter (ATC) Register, template 0x -
_9F14_LOWER_CONSECUTIVE_OFFLINE_LIMIT = 0x9F14,		// Lower Consecutive Offline Limit, template 0x 70|77
_9F15_MERCHANT_CATEGORY_CODE = 0x9F15,		// Merchant Category Code, template 0x -
_9F16_MERCHANT_IDENTIFIER = 0x9F16,		// Merchant Identifier, template 0x -
_9F17_PERSONAL_IDENTIFICATION_NUMBER_PIN_TRY_COUNTER = 0x9F17,		// Personal Identification Number (PIN) Try Counter, template 0x -
_9F18_ISSUER_SCRIPT_IDENTIFIER = 0x9F18,		// Issuer Script Identifier, template 0x 71|72
_9F1A_TERMINAL_COUNTRY_CODE = 0x9F1A,		// Terminal Country Code, template 0x -
_9F1B_TERMINAL_FLOOR_LIMIT = 0x9F1B,		// Terminal Floor Limit, template 0x -
_9F1C_TERMINAL_IDENTIFICATION = 0x9F1C,		// Terminal Identification, template 0x -
_9F1D_TERMINAL_RISK_MANAGEMENT_DATA = 0x9F1D,		// Terminal Risk Management Data, template 0x -
_9F1E_INTERFACE_DEVICE_IFD_SERIAL_NUMBER = 0x9F1E,		// Interface Device (IFD) Serial Number, template 0x -
_9F1F_TRACK_1_DISCRETIONARY_DATA = 0x9F1F,		// Track 1 Discretionary Data, template 0x 70|77
_9F20_TRACK_2_DISCRETIONARY_DATA = 0x9F20,		// Track 2 Discretionary Data, template 0x 70|77
_9F21_TRANSACTION_TIME = 0x9F21,		// Transaction Time, template 0x -
_9F22_CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX = 0x9F22,		// Certification Authority Public Key Index, template 0x -
_9F23_UPPER_CONSECUTIVE_OFFLINE_LIMIT = 0x9F23,		// Upper Consecutive Offline Limit, template 0x 70|77
_9F26_APPLICATION_CRYPTOGRAM = 0x9F26,		// Application Cryptogram, template 0x 77|80
_9F27_CRYPTOGRAM_INFORMATION_DATA = 0x9F27,		// Cryptogram Information Data, template 0x 77|80
_9F2D_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_CERTIFICATE = 0x9F2D,		// ICC PIN Encipherment Public Key Certificate, template 0x 70|77
_9F2E_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_EXPONENT = 0x9F2E,		// ICC PIN Encipherment Public Key Exponent, template 0x 70|77
_9F2F_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_REMAINDER = 0x9F2F,		// ICC PIN Encipherment Public Key Remainder, template 0x 70|77
_9F32_ISSUER_PUBLIC_KEY_EXPONENT = 0x9F32,		// Issuer Public Key Exponent, template 0x 70|77
_9F33_TERMINAL_CAPABILITIES = 0x9F33,		// Terminal Capabilities, template 0x -
_9F34_CARDHOLDER_VERIFICATION_METHOD_CVM_RESULTS = 0x9F34,		// Cardholder Verification Method (CVM) Results, template 0x -
_9F35_TERMINAL_TYPE = 0x9F35,		// Terminal Type, template 0x -
_9F36_APPLICATION_TRANSACTION_COUNTER_ATC = 0x9F36,		// Application Transaction Counter (ATC), template 0x 77|80
_9F37_UNPREDICTABLE_NUMBER = 0x9F37,		// Unpredictable Number, template 0x -
_9F38_PROCESSING_OPTIONS_DATA_OBJECT_LIST = 0x9F38,		// Processing Options Data Object List (PDOL), template 0x A5
_9F39_POINT_OF_SERVICE_POS_ENTRY_MODE = 0x9F39,		// Point-of-Service (POS) Entry Mode, template 0x -
_9F3A_AMOUNT_REFERENCE_CURENCY = 0x9F3A,		// Amount, Reference Currency, template 0x -
_9F3B_APPLICATION_REFERENCE_CURRENCY = 0x9F3B,		// Application Reference Currency, template 0x 70|77
_9F3C_TRANSACTION_REFERENCE_CURRENCY_CODE = 0x9F3C,		// Transaction Reference Currency Code, template 0x -
_9F3D_TRANSACTION_REFERENCE_CURRENCY_EXPONENT = 0x9F3D,		// Transaction Reference Currency Exponent, template 0x -
_9F40_ADDITIONAL_TERMINAL_CAPABILITIES = 0x9F40,		// Additional Terminal Capabilities, template 0x -
_9F41_TRANSACTION_SEQUENCE_COUNTER = 0x9F41,		// Transaction Sequence Counter, template 0x -
_9F42_APPLICATION_CURRENCY_CODE = 0x9F42,		// Application Currency Code, template 0x 70|77
_9F43_APPLICATION_REFERENCE_CURRENCY_EXPONENT = 0x9F43,		// Application Reference Currency Exponent, template 0x 70|77
_9F44_APPLICATION_CURRENCY_EXPONENT = 0x9F44,		// Application Currency Exponent, template 0x 70|77
_9F45_DATA_AUTHENTICATION_CODE = 0x9F45,		// Data Authentication Code, template 0x -
_9F46_ICC_PUBLIC_KEY_CERTIFICATE = 0x9F46,		// ICC Public Key Certificate, template 0x 70|77
_9F47_ICC_PUBLIC_KEY_EXPONENT = 0x9F47,		// ICC Public Key Exponent, template 0x 70|77
_9F48_ICC_PUBLIC_KEY_REMAINDER = 0x9F48,		// ICC Public Key Remainder, template 0x 70|77
_9F49_DYNAMIC_DATA_AUTHENTICATION_DATA_OBJECT_LIST_DDOL = 0x9F49,		// Dynamic Data Authentication Data Object List (DDOL), template 0x 70|77
_9F4A_STATIC_DATA_AUTHENTICATION_TAG_LIST = 0x9F4A,		// Static Data Authentication Tag List, template 0x 70|77
_9F4B_SIGNED_DYNAMIC_APPLICATION_DATA_ = 0x9F4B,		// Signed Dynamic Application Data , template 0x 77|80
_9F4C_ICC_DYNAMIC_NUMBER = 0x9F4C,		// ICC Dynamic Number, template 0x -
_9F4D_LOG_ENTRY = 0x9F4D,		// Log Entry, template 0x BF0C|73
_9F4E_MERCHANT_NAME_AND_LOCATION = 0x9F4E,		// Merchant Name and Location, template 0x -
_9F4F_LOG_FORMAT = 0x9F4F,		// Log Format, template 0x -
_A5_FILE_CONTROL_INFORMATION_FCI_PROPRIETARY_TEMPLATE = 0xA5,		// File Control Information (FCI) Proprietary Template, template 0x 6F
_BF0C_FILE_CONTROL_INFORMATION_FCI_ISSUER_DISCRETIONARY_DATA = 0xBF0C,		// File Control Information (FCI) Issuer Discretionary Data, template 0x A5
};

unsigned char taglist_sz = 121;
unsigned short taglist[] = 
{
_42_INN,
_4F_ADF,
_50_APP_LABEL,
_57_T2_EQ_DATA,
_5a_PAN,
_5F20_CARD_HOLDER_NAME,
_F24_APP_EXP_DATE,
_5F25_APP_EFF_DATE,
_5F28_ISSUER_COUNTRY_CODE,
_5F2A_TRANSACTION_CURRENCY_CODE,
_5F2D_LANG_PREFERENCE,
_5F30_SERVICE_CODE,
_5F34_PAN,
_5F36_TRANSACTION_CURENCY_EXPONENT,
_5F50_ISSUER_URL,
_5F53_IBAN,
_5F54_BIC,
_5F55_ISSUER_COUNTRY_CODE_A2F,
_5F56_ISSUER_COUNTRY_CODE_A3F,
_5F57_ACCOUNT_TYPE,
_61_APP_TEMPLATE,
_6F_FCI,
_70_READ_RECORD_RESPONSE_MESSAGE,
_71_ISSUER_SCRIPT_TEMPLATE_1,
_72_ISSUER_SCRIPT_TEMPLATE_2,
_73_DIRECTORY_DISCRETIONARY_TEMPLATE,
_77_RESPONSE_MESSAGE_TEMPLATE_FORMAT_2,
_80_RESPONSE_MESSAGE_TEMPLATE_FORMAT_1,
_81_AMOUNT_AUTHORISED,
_82_APPLICATION_INTERCHANGE_PROFILE,
_83_COMMAND_TEMPLATE,
_84_DEDICATED_FILE_DF_NAME,
_86_ISSUER_SCRIPT_COMMAND,
_87_APPLICATION_PRIORITY_INDICATOR,
_88_SHORT_FILE_IDENTIFIER_SFI,
_89_AUTHORISATION_CODE,
_8A_AUTHORISATION_RESPONSE_CODE,
_8C_CARD_RISK_MANAGEMENT_DATA_OBJECT_LIST1_CDOL1,
_8D_CARD_RISK_MANAGEMENT_DATA_OBJECT_LIST2_CDOL2,
_8E_CARDHOLDER_VERIFICATION_METHOD_CVM_LIST,
_8F_CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX,
_90_ISSUER_PUBLIC_KEY_CERTIFICATE,
_91_ISSUER_AUTHENTICATION_DATA,
_92_ISSUER_PUBLIC_KEY_REMAINDER,
_93_SIGNED_STATIC_APPLICATION_DATA,
_94_APPLICATION_FILE_LOCATOR_AFL,
_95_TERMINAL_VERIFICATION_RESULTS,
_97_TRANSACTION_CERTIFICATE_DATA_OBJECT_LIST_TDOL,
_98_TRANSACTION_CERTIFICATE_TC_HASH_VALUE,
_99_TRANSACTION_PERSONAL_IDENTIFICATION_NUMBER_PIN_DATA,
_9A_TRANSACTION_DATE,
_9B_TRANSACTION_STATUS_INFORMATION,
_9C_TRANSACTION_TYPE,
_9D_DIRECTORY_DEFINITION_FILE_DDF_NAME,
_9F01_ACQUIRER_IDENTIFIER,
_9F02_AMOUNT_AUTHORISED_NUMERIC,
_9F03_AMOUNT_OTHER_NUMERIC,
_9F04_AMOUNT_OTHER_BINARY,
_9F05_APPLICATION_DISCRETIONARY_DATA,
_9F06_APPLICATION_IDENTIFIER_AID_TERMINAL,
_9F07_APPLICATION_USAGE_CONTROL,
_9F08_APPLICATION_VERSION_NUMBER_T,
_9F09_APPLICATION_VERSION_NUMBER,
_9F0B_CARDHOLDER_NAME_EXTENDED,
_9F0D_ISSUER_ACTION_CODE_DEFAULT,
_9F0E_ISSUER_ACTION_CODE_DENIAL,
_9F0F_ISSUER_ACTION_CODE_ONLINE_,
_9F10_ISSUER_APPLICATION_DATA,
_9F11_ISSUER_CODE_TABLE_INDEX,
_9F12_APPLICATION_PREFERRED_NAME,
_9F13_LAST_ONLINE_APPLICATION_TRANSACTION_COUNTER_ATC_REGISTER,
_9F14_LOWER_CONSECUTIVE_OFFLINE_LIMIT,
_9F15_MERCHANT_CATEGORY_CODE,
_9F16_MERCHANT_IDENTIFIER,
_9F17_PERSONAL_IDENTIFICATION_NUMBER_PIN_TRY_COUNTER,
_9F18_ISSUER_SCRIPT_IDENTIFIER,
_9F1A_TERMINAL_COUNTRY_CODE,
_9F1B_TERMINAL_FLOOR_LIMIT,
_9F1C_TERMINAL_IDENTIFICATION,
_9F1D_TERMINAL_RISK_MANAGEMENT_DATA,
_9F1E_INTERFACE_DEVICE_IFD_SERIAL_NUMBER,
_9F1F_TRACK_1_DISCRETIONARY_DATA,
_9F20_TRACK_2_DISCRETIONARY_DATA,
_9F21_TRANSACTION_TIME,
_9F22_CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX,
_9F23_UPPER_CONSECUTIVE_OFFLINE_LIMIT,
_9F26_APPLICATION_CRYPTOGRAM,
_9F27_CRYPTOGRAM_INFORMATION_DATA,
_9F2D_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_CERTIFICATE,
_9F2E_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_EXPONENT,
_9F2F_ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_REMAINDER,
_9F32_ISSUER_PUBLIC_KEY_EXPONENT,
_9F33_TERMINAL_CAPABILITIES,
_9F34_CARDHOLDER_VERIFICATION_METHOD_CVM_RESULTS,
_9F35_TERMINAL_TYPE,
_9F36_APPLICATION_TRANSACTION_COUNTER_ATC,
_9F37_UNPREDICTABLE_NUMBER,
_9F38_PROCESSING_OPTIONS_DATA_OBJECT_LIST,
_9F39_POINT_OF_SERVICE_POS_ENTRY_MODE,
_9F3A_AMOUNT_REFERENCE_CURENCY,
_9F3B_APPLICATION_REFERENCE_CURRENCY,
_9F3C_TRANSACTION_REFERENCE_CURRENCY_CODE,
_9F3D_TRANSACTION_REFERENCE_CURRENCY_EXPONENT,
_9F40_ADDITIONAL_TERMINAL_CAPABILITIES,
_9F41_TRANSACTION_SEQUENCE_COUNTER,
_9F42_APPLICATION_CURRENCY_CODE,
_9F43_APPLICATION_REFERENCE_CURRENCY_EXPONENT,
_9F44_APPLICATION_CURRENCY_EXPONENT,
_9F45_DATA_AUTHENTICATION_CODE,
_9F46_ICC_PUBLIC_KEY_CERTIFICATE,
_9F47_ICC_PUBLIC_KEY_EXPONENT,
_9F48_ICC_PUBLIC_KEY_REMAINDER,
_9F49_DYNAMIC_DATA_AUTHENTICATION_DATA_OBJECT_LIST_DDOL,
_9F4A_STATIC_DATA_AUTHENTICATION_TAG_LIST,
_9F4B_SIGNED_DYNAMIC_APPLICATION_DATA_,
_9F4C_ICC_DYNAMIC_NUMBER,
_9F4D_LOG_ENTRY,
_9F4E_MERCHANT_NAME_AND_LOCATION,
_9F4F_LOG_FORMAT,
_A5_FILE_CONTROL_INFORMATION_FCI_PROPRIETARY_TEMPLATE,
_BF0C_FILE_CONTROL_INFORMATION_FCI_ISSUER_DISCRETIONARY_DATA};